stdout: stdout.c
	gcc -o stdout stdout.c -Wall

waitpid: waitpid.c
	gcc -o waitpid waitpid.c -Wall

wait: wait.c
	gcc -o wait wait.c -Wall

exec: exec.c
	gcc -o exec exec.c -Wall

hello2: hello2.c
	gcc -o hello2 hello2.c -Wall

hello: hello.c
	gcc -o hello hello.c -Wall

fork: fork.c 
	gcc -o fork fork.c -Wall

open: open.c
	gcc -o open open.c -Wall
	
